version: "3.2"
services:
  redis:
    image: redis
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - $PWD/.docker_data/redis:/data
    profiles:
      - app
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - $PWD/.docker_data/rabbitmq/data/:/var/lib/rabbitmq/
      - $PWD/.docker_data/rabbitmq/log/:/var/log/rabbitmq
    environment: 
      RABBITMQ_DEFAULT_USER: someuser
      RABBITMQ_DEFAULT_PASS: supersecurepass3
    profiles:
      - mq
  
  postgres:
    image: postgres:latest
    container_name: postgres
    network_mode: bridge
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_DB: testing
      POSTGRES_PASSWORD: admin
    volumes:
      - $PWD/.docker_data/database-data:/var/lib/postgresql/data/
    profiles:
      - db